### ISSUE TITLE
Asset <-> Contact Handling

### ISSUE THREAD

**Issue by KaiDol** [inofix/liferay-modules#21] opened 2015-06-30 19:18 UTC
When previewing a contact an asset-list is shown. When I click on one asset, it opens up, but sometimes with the whole Website (see example "Maria Berning") - not only the assets frame
Within the asset (memo for instance): when I click on the contact as linked asset it opens up the contact list and not the selected contact.
see screenshot 
![bildschirmfoto 2015-06-30 um 21 11 40](https://cloud.githubusercontent.com/assets/6461005/8439596/646c8e28-1f6d-11e5-98ea-c784ac51dbfe.png)

![bildschirmfoto 2015-06-30 um 21 11 48](https://cloud.githubusercontent.com/assets/6461005/8439595/64655860-1f6d-11e5-85eb-282404781daf.png)

![bildschirmfoto 2015-06-30 um 21 11 55](https://cloud.githubusercontent.com/assets/6461005/8439594/643cdade-1f6d-11e5-8862-c71fa4fde3a2.png)

**Comment by chrberndt** [comment] 2015-07-01 06:28
This is a bug of liferay proper, but we have a solution at hand.

**Comment by chrberndt** [comment] 2015-07-01 13:11
The issue is fixed and committed and will be deployed with snapshot 0.5.0

**Closed by chrberndt** 2015-07-01 13:11 UTC
Labels: bug
